eureka:
  instance:
    #每一秒想注册中心发送一次心跳检测
    lease-renewal-interval-in-seconds: 1
    #如果两秒钟没有发送心跳检测,则证明该服务已死亡
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-b:
      path: /api-feign/**
      serviceId: service-feign

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
